### ISSUE TITLE
Compilation error when building profile for Android

### ISSUE THREAD

**Issue by martarek** [volatilityfoundation/volatility#101]
When making a Linux profile for Android (v4.2.2r2) using the following makefile

```
obj-m += module.o
KDIR := ~/android/msm/ 
CC_PATH :=  ~/android/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/

-include version.mk
all: dwarf
dwarf: module.c
	$(MAKE) ARCH=arm CROSS_COMPILE=$(CC_PATH)/arm-linux-androideabi- -C $(KDIR) CONFIG_DEBUG_INFO=y M=$(PWD) modules 
	dwarfdump -di module.ko > module.dwarf 

clean:
	$(MAKE) -C $(KDIR)/lib/modules/$(KVER)/build M=$(PWD) clean
	rm -f module.dwarf
```
I get the following error at compilation :

```
  CC [M]  ./volatility/tools/linux/module.o
./volatility/tools/linux/module.c:183:0: warning: "RADIX_TREE_MAX_TAGS" redefined [enabled by default]
error, forbidden warning: module.c:183
make[2]: *** [./volatility/tools/linux/module.o] Error 1
make[1]: *** [_module_./volatility/tools/linux] Error 2
make[1]: Leaving directory `~/android/msm'
make: *** [dwarf] Error 2
```
If I comment out line 183 :
#define RADIX_TREE_MAX_TAGS     2

The compilation runs fine but the resulting profile creates unexpected behavior when used for analysis. For instance linux_check_inline_kernel returns unexpected values :

```
Name                                             Member           Hook Type Hook Address
------------------------------------------------ ---------------- --------- ------------
//                                               llseek           JMP       0x0000000000
//                                               readdir          JMP       0x0000000000
```
While if it is executed with the previous profile I had from volatility v2.3.1 I get :

```
Name                                             Member           Hook Type Hook Address
------------------------------------------------ ---------------- --------- ------------
init 4 /dev/__properties__                       llseek           JMP       0x0000000000
init 4 /dev/__properties__                       mmap             JMP       0x0000000000
```

At the end of this output I get the message that my Volatility profile is outdated and should be recompiled using latest version's tools.

The expected behavior would be a profile that build correctly without modifying module.c and that works with plugins.

**Comment by atcuno** [comment]
Fixed: https://github.com/volatilityfoundation/volatility/commit/ec44ae49c00945fc6bda702c6a16a8cb446d2401

Please let me know if you havve any issues in the future.

**Comment by kmm2** [comment]
I have the same issue:
```
.../volatility/tools/linux/module.c:183:0: warning: "RADIX_TREE_MAX_TAGS" redefined [enabled by default]
error, forbidden warning: module.c:183
```
Why is the master version still buggy? When I switched to the 2015 ec44ae4 it was OK.

**Comment by LeoColomb** [comment]
I have the same issue, right now, with Android 7.1.
The commit that "breaks" the fix is 044910f6b3253d8e35aa2bf79cc8186720c5ff62.
And reverting that commit even over master works well! 😺
